services:
  qbittorrent:
    image: vpn-qbit
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.all.disable_ipv6=1
    environment:
      - VPN_ENABLED=true
      - VPN_DNS=1.1.1.1
      - VPN_PORT=35578
    volumes:
      - ./config:/config
      - ./data:/data
    ports:
      - 8080:8080
